version: '2'

services:
  cassandra:
    image: cassandra:2.2.6
    container_name: kong-database
    restart: always
    ports:
      - 9042:9042
  kong:
    image: superpixel/kong-plugin-development
    container_name: kong
    restart: always
    ports:
      - 8000:8000
      - 8001:8001
      - 8443:8443
      - 7946:7946
      - 7946:7946/udp
    volumes:
      - ./config:/etc/kong/
      - ./plugins:/plugins
    links:
      - cassandra:kong-database
    security_opt:
      - label:seccomp:unconfined
    depends_on:
      - cassandra